// <auto-generated />
using System;
using Imu.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imu.Api.Migrations;

[DbContext(typeof(ImuDbContext))]
[Migration("20231214112642_KafkaMigration")]
partial class KafkaMigration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Imu.Repository.Model.AnagraficaImmobile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("IdAnagrafica")
                    .HasColumnType("int");

                b.Property<int>("IdImmobile")
                    .HasColumnType("int");

                b.Property<decimal>("Quota")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("IdImmobile");

                b.ToTable("AnagraficheImmobili");
            });

        modelBuilder.Entity("Imu.Repository.Model.CategoriaCatastale", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Codice")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Descrizione")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("CategorieCatastali");
            });

        modelBuilder.Entity("Imu.Repository.Model.Immobile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Cap")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Foglio")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("IdCategoriaCatastale")
                    .HasColumnType("int");

                b.Property<string>("Indirizzo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Localita")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NumeroCivico")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Particella")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Provincia")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Rendita")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Sezione")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Subalterno")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Superficie")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("IdCategoriaCatastale");

                b.ToTable("Immobili");
            });

        modelBuilder.Entity("Imu.Repository.Model.TransactionalOutbox", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Messaggio")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Tabella")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("TransactionalOutboxList");
            });

        modelBuilder.Entity("Imu.Repository.Model.VersamentoKafka", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DataContabile")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DataVersamento")
                    .HasColumnType("datetime2");

                b.Property<decimal>("Importo")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Informazioni")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("VersamentiKafka");
            });

        modelBuilder.Entity("Imu.Repository.Model.AnagraficaImmobile", b =>
            {
                b.HasOne("Imu.Repository.Model.Immobile", "Immobile")
                    .WithMany("AnagraficheImmobile")
                    .HasForeignKey("IdImmobile")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Immobile");
            });

        modelBuilder.Entity("Imu.Repository.Model.Immobile", b =>
            {
                b.HasOne("Imu.Repository.Model.CategoriaCatastale", "CategoriaCatastale")
                    .WithMany("Immobili")
                    .HasForeignKey("IdCategoriaCatastale")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CategoriaCatastale");
            });

        modelBuilder.Entity("Imu.Repository.Model.CategoriaCatastale", b =>
            {
                b.Navigation("Immobili");
            });

        modelBuilder.Entity("Imu.Repository.Model.Immobile", b =>
            {
                b.Navigation("AnagraficheImmobile");
            });
#pragma warning restore 612, 618
    }
}
